#config Discovery server

spring:
  application:
    name: fileuploader
    

eureka:
  client:
   serviceUrl:
    defaultZone: http://localhost:8761/eureka, http://localhost:8762/eureka
  

server:
  port: 2349