#config Discovery server

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false

server:
  port: 8761
  
  
# OR application.propperties =
#spring.application.name=eureka-service
#server.port=${PORT:8761}
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
 