#config Discovery server
spring:
  application:
    name: eureka

eureka:
  instance: 
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka
    registerWithEureka: true
    fetchRegistry: true
server:
  port: 8761
  

 
 
 
 
  
# OR application.propperties =
#spring.application.name=eureka-service
#server.port=${PORT:8761}
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
 