#config Discovery server

spring:  application:    name: eureka

eureka:
  instance: 
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
server:
  port: 8762
 
 
 
  
# OR application.propperties =
#spring.application.name=eureka-service
#server.port=${PORT:8761}
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
 