##config Discovery server
#
#spring:
#  application:
#    name: family_calendar
#    
#
#eureka:
#  client:
#   serviceUrl:
#    defaultZone: http://localhost:8761/eureka
#  

#server:
#  port: 9000

#defaultZone: http://peer1/eureka/,http://peer2/eureka/,http://peer3/eureka/